# Automatically generated by SST
import sst

# Define SST Program Options:
sst.setProgramOption("timebase", "1ps")
sst.setProgramOption("stopAtCycle", "0 ns")

# Define the SST Components:
comp_cpu_xbar = sst.Component("cpu_xbar", "shogun.ShogunXBar")
comp_cpu_xbar.addParams({
     "buffer_depth" : "64",
     "clock" : "1200MHz",
     "debug" : "0",
     "debug_level" : "10",
     "input_message_slots" : "3",
     "output_message_slots" : "3",
     "port_count" : "12",
     "verbose" : "0"
})
comp_cpu_xbar.setCoordinates(0, 0, 0)
comp_cpu_xbar.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000001 = sst.Link("link_id_00000001")
comp_cpu_xbar.addLink(link_id_00000001, "port0", "100ps")
link_id_00000003 = sst.Link("link_id_00000003")
comp_cpu_xbar.addLink(link_id_00000003, "port1", "100ps")
link_id_00000005 = sst.Link("link_id_00000005")
comp_cpu_xbar.addLink(link_id_00000005, "port2", "100ps")
link_id_00000007 = sst.Link("link_id_00000007")
comp_cpu_xbar.addLink(link_id_00000007, "port3", "100ps")
link_id_00000009 = sst.Link("link_id_00000009")
comp_cpu_xbar.addLink(link_id_00000009, "port4", "100ps")
link_id_0000000b = sst.Link("link_id_0000000b")
comp_cpu_xbar.addLink(link_id_0000000b, "port5", "100ps")
link_id_0000000d = sst.Link("link_id_0000000d")
comp_cpu_xbar.addLink(link_id_0000000d, "port6", "100ps")
link_id_0000000f = sst.Link("link_id_0000000f")
comp_cpu_xbar.addLink(link_id_0000000f, "port7", "100ps")
link_id_00000014 = sst.Link("link_id_00000014")
comp_cpu_xbar.addLink(link_id_00000014, "port8", "100ps")
link_id_0000001a = sst.Link("link_id_0000001a")
comp_cpu_xbar.addLink(link_id_0000001a, "port9", "100ps")
link_id_00000020 = sst.Link("link_id_00000020")
comp_cpu_xbar.addLink(link_id_00000020, "port10", "100ps")
link_id_00000026 = sst.Link("link_id_00000026")
comp_cpu_xbar.addLink(link_id_00000026, "port11", "100ps")
comp_cpu_0 = sst.Component("cpu_0", "miranda.BaseCPU")
comp_cpu_0.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "2147483648",
     "generatorParams.startat" : "0",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_0.setCoordinates(0, 0, 0)
comp_cpu_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000000 = sst.Link("link_id_00000000")
comp_cpu_0.addLink(link_id_00000000, "cache_link", "100ps")
comp_l1cache_0 = sst.Component("l1cache_0", "memHierarchy.Cache")
comp_l1cache_0.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_0.setCoordinates(0, 0, 0)
comp_l1cache_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_0.addLink(link_id_00000000, "high_network_0", "100ps")
comp_l1cache_0.addLink(link_id_00000001, "cache", "100ps")
comp_cpu_1 = sst.Component("cpu_1", "miranda.BaseCPU")
comp_cpu_1.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "4294967296",
     "generatorParams.startat" : "2147483648",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_1.setCoordinates(0, 0, 0)
comp_cpu_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000002 = sst.Link("link_id_00000002")
comp_cpu_1.addLink(link_id_00000002, "cache_link", "100ps")
comp_l1cache_1 = sst.Component("l1cache_1", "memHierarchy.Cache")
comp_l1cache_1.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_1.setCoordinates(0, 0, 0)
comp_l1cache_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_1.addLink(link_id_00000002, "high_network_0", "100ps")
comp_l1cache_1.addLink(link_id_00000003, "cache", "100ps")
comp_cpu_2 = sst.Component("cpu_2", "miranda.BaseCPU")
comp_cpu_2.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "6442450944",
     "generatorParams.startat" : "4294967296",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_2.setCoordinates(0, 0, 0)
comp_cpu_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000004 = sst.Link("link_id_00000004")
comp_cpu_2.addLink(link_id_00000004, "cache_link", "100ps")
comp_l1cache_2 = sst.Component("l1cache_2", "memHierarchy.Cache")
comp_l1cache_2.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_2.setCoordinates(0, 0, 0)
comp_l1cache_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_2.addLink(link_id_00000004, "high_network_0", "100ps")
comp_l1cache_2.addLink(link_id_00000005, "cache", "100ps")
comp_cpu_3 = sst.Component("cpu_3", "miranda.BaseCPU")
comp_cpu_3.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "8589934592",
     "generatorParams.startat" : "6442450944",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_3.setCoordinates(0, 0, 0)
comp_cpu_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000006 = sst.Link("link_id_00000006")
comp_cpu_3.addLink(link_id_00000006, "cache_link", "100ps")
comp_l1cache_3 = sst.Component("l1cache_3", "memHierarchy.Cache")
comp_l1cache_3.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_3.setCoordinates(0, 0, 0)
comp_l1cache_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_3.addLink(link_id_00000006, "high_network_0", "100ps")
comp_l1cache_3.addLink(link_id_00000007, "cache", "100ps")
comp_cpu_4 = sst.Component("cpu_4", "miranda.BaseCPU")
comp_cpu_4.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "10737418240",
     "generatorParams.startat" : "8589934592",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_4.setCoordinates(0, 0, 0)
comp_cpu_4.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000008 = sst.Link("link_id_00000008")
comp_cpu_4.addLink(link_id_00000008, "cache_link", "100ps")
comp_l1cache_4 = sst.Component("l1cache_4", "memHierarchy.Cache")
comp_l1cache_4.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_4.setCoordinates(0, 0, 0)
comp_l1cache_4.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_4.addLink(link_id_00000008, "high_network_0", "100ps")
comp_l1cache_4.addLink(link_id_00000009, "cache", "100ps")
comp_cpu_5 = sst.Component("cpu_5", "miranda.BaseCPU")
comp_cpu_5.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "12884901888",
     "generatorParams.startat" : "10737418240",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_5.setCoordinates(0, 0, 0)
comp_cpu_5.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_0000000a = sst.Link("link_id_0000000a")
comp_cpu_5.addLink(link_id_0000000a, "cache_link", "100ps")
comp_l1cache_5 = sst.Component("l1cache_5", "memHierarchy.Cache")
comp_l1cache_5.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_5.setCoordinates(0, 0, 0)
comp_l1cache_5.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_5.addLink(link_id_0000000a, "high_network_0", "100ps")
comp_l1cache_5.addLink(link_id_0000000b, "cache", "100ps")
comp_cpu_6 = sst.Component("cpu_6", "miranda.BaseCPU")
comp_cpu_6.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "15032385536",
     "generatorParams.startat" : "12884901888",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_6.setCoordinates(0, 0, 0)
comp_cpu_6.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_0000000c = sst.Link("link_id_0000000c")
comp_cpu_6.addLink(link_id_0000000c, "cache_link", "100ps")
comp_l1cache_6 = sst.Component("l1cache_6", "memHierarchy.Cache")
comp_l1cache_6.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_6.setCoordinates(0, 0, 0)
comp_l1cache_6.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_6.addLink(link_id_0000000c, "high_network_0", "100ps")
comp_l1cache_6.addLink(link_id_0000000d, "cache", "100ps")
comp_cpu_7 = sst.Component("cpu_7", "miranda.BaseCPU")
comp_cpu_7.addParams({
     "clock" : "2100MHz",
     "generator" : "miranda.SingleStreamGenerator",
     "generatorParams.count" : "600000",
     "generatorParams.length" : "64",
     "generatorParams.max_address" : "17179869184",
     "generatorParams.startat" : "15032385536",
     "generatorParams.verbose" : "0",
     "max_reqs_cycle" : "4",
     "maxmemreqpending" : "64",
     "verbose" : "0"
})
comp_cpu_7.setCoordinates(0, 0, 0)
comp_cpu_7.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_0000000e = sst.Link("link_id_0000000e")
comp_cpu_7.addLink(link_id_0000000e, "cache_link", "100ps")
comp_l1cache_7 = sst.Component("l1cache_7", "memHierarchy.Cache")
comp_l1cache_7.addParams({
     "L1" : "1",
     "access_latency_cycles" : "4",
     "associativity" : "8",
     "cache_frequency" : "1200MHz",
     "cache_line_size" : "64",
     "cache_size" : "32KB",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "verbose" : "0"
})
comp_l1cache_7.setCoordinates(0, 0, 0)
comp_l1cache_7.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l1cache_7.addLink(link_id_0000000e, "high_network_0", "100ps")
comp_l1cache_7.addLink(link_id_0000000f, "cache", "100ps")
comp_mem_l2_bus_0 = sst.Component("mem_l2_bus_0", "memHierarchy.Bus")
comp_mem_l2_bus_0.addParams({
     "bus_frequency" : "4GHz",
     "drain_bus" : "1"
})
comp_mem_l2_bus_0.setCoordinates(0, 0, 0)
comp_mem_l2_bus_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000013 = sst.Link("link_id_00000013")
comp_mem_l2_bus_0.addLink(link_id_00000013, "low_network_0", "100ps")
link_id_00000015 = sst.Link("link_id_00000015")
comp_mem_l2_bus_0.addLink(link_id_00000015, "high_network_0", "100ps")
comp_GPUhbm_0 = sst.Component("GPUhbm_0", "memHierarchy.MemController")
comp_GPUhbm_0.addParams({
     "backend" : "memHierarchy.cramsim",
     "backend.access_time" : "1ns",
     "backend.max_outstanding_requests" : "102400",
     "backend.mem_size" : "17179869184B",
     "backend.request_width" : "64",
     "backing" : "none",
     "clock" : "877MHz",
     "cpulink.accept_region" : "0",
     "cpulink.ack.network_bw" : "32GB/s",
     "cpulink.addr_range_end" : "17179868160",
     "cpulink.addr_range_start" : "0",
     "cpulink.data.network_bw" : "32GB/s",
     "cpulink.fwd.network_bw" : "32GB/s",
     "cpulink.interleave_size" : "256B",
     "cpulink.interleave_step" : "1024B",
     "cpulink.req.network_bw" : "32GB/s",
     "debug" : "0",
     "debug_level" : "10",
     "max_requests_per_cycle" : "-1",
     "verbose" : "0"
})
comp_GPUhbm_0.setCoordinates(0, 0, 0)
comp_GPUhbm_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000010 = sst.Link("link_id_00000010")
comp_GPUhbm_0.addLink(link_id_00000010, "cube_link", "2000ps")
comp_GPUhbm_0.addLink(link_id_00000013, "direct_link", "100ps")
comp_hbm_cs_bridge_0 = sst.Component("hbm_cs_bridge_0", "CramSim.c_MemhBridge")
comp_hbm_cs_bridge_0.addParams({
     "debug" : "0",
     "debug_level" : "10",
     "maxOutstandingReqs" : "102400",
     "mode" : "seq",
     "numBytesPerTransaction" : "32",
     "numTxnPerCycle" : "8",
     "randomSeed" : "0",
     "readWriteRatio" : "0.667",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_bridge_0.setCoordinates(0, 0, 0)
comp_hbm_cs_bridge_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_bridge_0.addLink(link_id_00000010, "cpuLink", "2000ps")
link_id_00000011 = sst.Link("link_id_00000011")
comp_hbm_cs_bridge_0.addLink(link_id_00000011, "memLink", "1000ps")
comp_hbm_cs_ctrl_0 = sst.Component("hbm_cs_ctrl_0", "CramSim.c_Controller")
comp_hbm_cs_ctrl_0.addParams({
     "AddrMapper" : "CramSim.c_AddressHasher",
     "CmdScheduler" : "CramSim.c_CmdScheduler",
     "DeviceDriver" : "CramSim.c_DeviceDriver",
     "TxnConverter" : "CramSim.c_TxnConverter",
     "TxnScheduler" : "CramSim.c_TxnScheduler",
     "bankPolicy" : "OPEN",
     "boolDualCommandBus" : "1",
     "boolEnableQuickRes" : "0",
     "boolMultiCycleACT" : "1",
     "boolReadFirstTxnScheduling" : "0",
     "boolUseReadA" : "0",
     "boolUseRefresh" : "1",
     "boolUseSBRefresh" : "0",
     "boolUseWriteA" : "0",
     "cmdSchedulingPolicy" : "BANK",
     "debug" : "0",
     "debug_level" : "10",
     "maxPendingWriteThreshold" : "1",
     "minPendingWriteThreshold" : "0.2",
     "nAL" : "0",
     "nBL" : "2",
     "nCCD" : "2",
     "nCCD_L" : "4",
     "nCCD_L_WR" : "2",
     "nCCD_S" : "2",
     "nCL" : "12",
     "nCWL" : "4",
     "nERTR" : "6",
     "nERTW" : "6",
     "nEWTR" : "6",
     "nEWTW" : "6",
     "nFAW" : "16",
     "nRAS" : "28",
     "nRC" : "40",
     "nRCD" : "12",
     "nREFI" : "3900",
     "nRFC" : "350",
     "nRP" : "12",
     "nRRD" : "3",
     "nRRD_L" : "3",
     "nRRD_S" : "2",
     "nRTP" : "3",
     "nRTW" : "13",
     "nWR" : "10",
     "nWTR" : "2",
     "nWTR_L" : "6",
     "nWTR_S" : "3",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numBytesPerTransaction" : "64",
     "numChannels" : "8",
     "numCmdQEntries" : "32",
     "numColsPerBank" : "64",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "numRowsPerBank" : "16384",
     "numTxnQEntries" : "1024",
     "relCommandWidth" : "1",
     "strAddressMapStr" : "r:14_b:2_B:2_l:3_C:3_l:3_c:1_h:6_",
     "strControllerClockFrequency" : "877MHz",
     "txnSchedulingPolicy" : "FRFCFS",
     "verbose" : "0"
})
comp_hbm_cs_ctrl_0.setCoordinates(0, 0, 0)
comp_hbm_cs_ctrl_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_ctrl_0.addLink(link_id_00000011, "txngenLink", "1000ps")
link_id_00000012 = sst.Link("link_id_00000012")
comp_hbm_cs_ctrl_0.addLink(link_id_00000012, "memLink", "1000ps")
comp_hbm_cs_dimm_0 = sst.Component("hbm_cs_dimm_0", "CramSim.c_Dimm")
comp_hbm_cs_dimm_0.addParams({
     "boolPowerCalc" : "0",
     "debug" : "0",
     "debug_level" : "10",
     "nRAS" : "28",
     "nRP" : "12",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numChannels" : "8",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_dimm_0.setCoordinates(0, 0, 0)
comp_hbm_cs_dimm_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_dimm_0.addLink(link_id_00000012, "ctrlLink", "1000ps")
comp_l2cache_0 = sst.Component("l2cache_0", "memHierarchy.Cache")
comp_l2cache_0.addParams({
     "access_latency_cycles" : "100",
     "associativity" : "96",
     "cache_frequency" : "1312MHz",
     "cache_line_size" : "64",
     "cache_size" : "192KiB",
     "cache_type" : "noninclusive",
     "coherence_protocol" : "MESI",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.addr_range_end" : "17179868160",
     "memNIC.addr_range_start" : "0",
     "memNIC.group" : "2",
     "memNIC.interleave_size" : "256B",
     "memNIC.interleave_step" : "1024B",
     "memNIC.network_bw" : "37.5GB/s",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "mshr_num_entries" : "2048",
     "replacement_policy" : "lru",
     "verbose" : "2"
})
comp_l2cache_0.setCoordinates(0, 0, 0)
comp_l2cache_0.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l2cache_0.addLink(link_id_00000014, "cache", "100ps")
comp_l2cache_0.addLink(link_id_00000015, "low_network_0", "100ps")
comp_mem_l2_bus_1 = sst.Component("mem_l2_bus_1", "memHierarchy.Bus")
comp_mem_l2_bus_1.addParams({
     "bus_frequency" : "4GHz",
     "drain_bus" : "1"
})
comp_mem_l2_bus_1.setCoordinates(0, 0, 0)
comp_mem_l2_bus_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000019 = sst.Link("link_id_00000019")
comp_mem_l2_bus_1.addLink(link_id_00000019, "low_network_0", "100ps")
link_id_0000001b = sst.Link("link_id_0000001b")
comp_mem_l2_bus_1.addLink(link_id_0000001b, "high_network_0", "100ps")
comp_GPUhbm_1 = sst.Component("GPUhbm_1", "memHierarchy.MemController")
comp_GPUhbm_1.addParams({
     "backend" : "memHierarchy.cramsim",
     "backend.access_time" : "1ns",
     "backend.max_outstanding_requests" : "102400",
     "backend.mem_size" : "17179869184B",
     "backend.request_width" : "64",
     "backing" : "none",
     "clock" : "877MHz",
     "cpulink.accept_region" : "0",
     "cpulink.ack.network_bw" : "32GB/s",
     "cpulink.addr_range_end" : "17179868416",
     "cpulink.addr_range_start" : "256",
     "cpulink.data.network_bw" : "32GB/s",
     "cpulink.fwd.network_bw" : "32GB/s",
     "cpulink.interleave_size" : "256B",
     "cpulink.interleave_step" : "1024B",
     "cpulink.req.network_bw" : "32GB/s",
     "debug" : "0",
     "debug_level" : "10",
     "max_requests_per_cycle" : "-1",
     "verbose" : "0"
})
comp_GPUhbm_1.setCoordinates(0, 0, 0)
comp_GPUhbm_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000016 = sst.Link("link_id_00000016")
comp_GPUhbm_1.addLink(link_id_00000016, "cube_link", "2000ps")
comp_GPUhbm_1.addLink(link_id_00000019, "direct_link", "100ps")
comp_hbm_cs_bridge_1 = sst.Component("hbm_cs_bridge_1", "CramSim.c_MemhBridge")
comp_hbm_cs_bridge_1.addParams({
     "debug" : "0",
     "debug_level" : "10",
     "maxOutstandingReqs" : "102400",
     "mode" : "seq",
     "numBytesPerTransaction" : "32",
     "numTxnPerCycle" : "8",
     "randomSeed" : "0",
     "readWriteRatio" : "0.667",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_bridge_1.setCoordinates(0, 0, 0)
comp_hbm_cs_bridge_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_bridge_1.addLink(link_id_00000016, "cpuLink", "2000ps")
link_id_00000017 = sst.Link("link_id_00000017")
comp_hbm_cs_bridge_1.addLink(link_id_00000017, "memLink", "1000ps")
comp_hbm_cs_ctrl_1 = sst.Component("hbm_cs_ctrl_1", "CramSim.c_Controller")
comp_hbm_cs_ctrl_1.addParams({
     "AddrMapper" : "CramSim.c_AddressHasher",
     "CmdScheduler" : "CramSim.c_CmdScheduler",
     "DeviceDriver" : "CramSim.c_DeviceDriver",
     "TxnConverter" : "CramSim.c_TxnConverter",
     "TxnScheduler" : "CramSim.c_TxnScheduler",
     "bankPolicy" : "OPEN",
     "boolDualCommandBus" : "1",
     "boolEnableQuickRes" : "0",
     "boolMultiCycleACT" : "1",
     "boolReadFirstTxnScheduling" : "0",
     "boolUseReadA" : "0",
     "boolUseRefresh" : "1",
     "boolUseSBRefresh" : "0",
     "boolUseWriteA" : "0",
     "cmdSchedulingPolicy" : "BANK",
     "debug" : "0",
     "debug_level" : "10",
     "maxPendingWriteThreshold" : "1",
     "minPendingWriteThreshold" : "0.2",
     "nAL" : "0",
     "nBL" : "2",
     "nCCD" : "2",
     "nCCD_L" : "4",
     "nCCD_L_WR" : "2",
     "nCCD_S" : "2",
     "nCL" : "12",
     "nCWL" : "4",
     "nERTR" : "6",
     "nERTW" : "6",
     "nEWTR" : "6",
     "nEWTW" : "6",
     "nFAW" : "16",
     "nRAS" : "28",
     "nRC" : "40",
     "nRCD" : "12",
     "nREFI" : "3900",
     "nRFC" : "350",
     "nRP" : "12",
     "nRRD" : "3",
     "nRRD_L" : "3",
     "nRRD_S" : "2",
     "nRTP" : "3",
     "nRTW" : "13",
     "nWR" : "10",
     "nWTR" : "2",
     "nWTR_L" : "6",
     "nWTR_S" : "3",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numBytesPerTransaction" : "64",
     "numChannels" : "8",
     "numCmdQEntries" : "32",
     "numColsPerBank" : "64",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "numRowsPerBank" : "16384",
     "numTxnQEntries" : "1024",
     "relCommandWidth" : "1",
     "strAddressMapStr" : "r:14_b:2_B:2_l:3_C:3_l:3_c:1_h:6_",
     "strControllerClockFrequency" : "877MHz",
     "txnSchedulingPolicy" : "FRFCFS",
     "verbose" : "0"
})
comp_hbm_cs_ctrl_1.setCoordinates(0, 0, 0)
comp_hbm_cs_ctrl_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_ctrl_1.addLink(link_id_00000017, "txngenLink", "1000ps")
link_id_00000018 = sst.Link("link_id_00000018")
comp_hbm_cs_ctrl_1.addLink(link_id_00000018, "memLink", "1000ps")
comp_hbm_cs_dimm_1 = sst.Component("hbm_cs_dimm_1", "CramSim.c_Dimm")
comp_hbm_cs_dimm_1.addParams({
     "boolPowerCalc" : "0",
     "debug" : "0",
     "debug_level" : "10",
     "nRAS" : "28",
     "nRP" : "12",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numChannels" : "8",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_dimm_1.setCoordinates(0, 0, 0)
comp_hbm_cs_dimm_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_dimm_1.addLink(link_id_00000018, "ctrlLink", "1000ps")
comp_l2cache_1 = sst.Component("l2cache_1", "memHierarchy.Cache")
comp_l2cache_1.addParams({
     "access_latency_cycles" : "100",
     "associativity" : "96",
     "cache_frequency" : "1312MHz",
     "cache_line_size" : "64",
     "cache_size" : "192KiB",
     "cache_type" : "noninclusive",
     "coherence_protocol" : "MESI",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.addr_range_end" : "17179868416",
     "memNIC.addr_range_start" : "256",
     "memNIC.group" : "2",
     "memNIC.interleave_size" : "256B",
     "memNIC.interleave_step" : "1024B",
     "memNIC.network_bw" : "37.5GB/s",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "mshr_num_entries" : "2048",
     "replacement_policy" : "lru",
     "verbose" : "2"
})
comp_l2cache_1.setCoordinates(0, 0, 0)
comp_l2cache_1.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l2cache_1.addLink(link_id_0000001a, "cache", "100ps")
comp_l2cache_1.addLink(link_id_0000001b, "low_network_0", "100ps")
comp_mem_l2_bus_2 = sst.Component("mem_l2_bus_2", "memHierarchy.Bus")
comp_mem_l2_bus_2.addParams({
     "bus_frequency" : "4GHz",
     "drain_bus" : "1"
})
comp_mem_l2_bus_2.setCoordinates(0, 0, 0)
comp_mem_l2_bus_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_0000001f = sst.Link("link_id_0000001f")
comp_mem_l2_bus_2.addLink(link_id_0000001f, "low_network_0", "100ps")
link_id_00000021 = sst.Link("link_id_00000021")
comp_mem_l2_bus_2.addLink(link_id_00000021, "high_network_0", "100ps")
comp_GPUhbm_2 = sst.Component("GPUhbm_2", "memHierarchy.MemController")
comp_GPUhbm_2.addParams({
     "backend" : "memHierarchy.cramsim",
     "backend.access_time" : "1ns",
     "backend.max_outstanding_requests" : "102400",
     "backend.mem_size" : "17179869184B",
     "backend.request_width" : "64",
     "backing" : "none",
     "clock" : "877MHz",
     "cpulink.accept_region" : "0",
     "cpulink.ack.network_bw" : "32GB/s",
     "cpulink.addr_range_end" : "17179868672",
     "cpulink.addr_range_start" : "512",
     "cpulink.data.network_bw" : "32GB/s",
     "cpulink.fwd.network_bw" : "32GB/s",
     "cpulink.interleave_size" : "256B",
     "cpulink.interleave_step" : "1024B",
     "cpulink.req.network_bw" : "32GB/s",
     "debug" : "0",
     "debug_level" : "10",
     "max_requests_per_cycle" : "-1",
     "verbose" : "0"
})
comp_GPUhbm_2.setCoordinates(0, 0, 0)
comp_GPUhbm_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_0000001c = sst.Link("link_id_0000001c")
comp_GPUhbm_2.addLink(link_id_0000001c, "cube_link", "2000ps")
comp_GPUhbm_2.addLink(link_id_0000001f, "direct_link", "100ps")
comp_hbm_cs_bridge_2 = sst.Component("hbm_cs_bridge_2", "CramSim.c_MemhBridge")
comp_hbm_cs_bridge_2.addParams({
     "debug" : "0",
     "debug_level" : "10",
     "maxOutstandingReqs" : "102400",
     "mode" : "seq",
     "numBytesPerTransaction" : "32",
     "numTxnPerCycle" : "8",
     "randomSeed" : "0",
     "readWriteRatio" : "0.667",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_bridge_2.setCoordinates(0, 0, 0)
comp_hbm_cs_bridge_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_bridge_2.addLink(link_id_0000001c, "cpuLink", "2000ps")
link_id_0000001d = sst.Link("link_id_0000001d")
comp_hbm_cs_bridge_2.addLink(link_id_0000001d, "memLink", "1000ps")
comp_hbm_cs_ctrl_2 = sst.Component("hbm_cs_ctrl_2", "CramSim.c_Controller")
comp_hbm_cs_ctrl_2.addParams({
     "AddrMapper" : "CramSim.c_AddressHasher",
     "CmdScheduler" : "CramSim.c_CmdScheduler",
     "DeviceDriver" : "CramSim.c_DeviceDriver",
     "TxnConverter" : "CramSim.c_TxnConverter",
     "TxnScheduler" : "CramSim.c_TxnScheduler",
     "bankPolicy" : "OPEN",
     "boolDualCommandBus" : "1",
     "boolEnableQuickRes" : "0",
     "boolMultiCycleACT" : "1",
     "boolReadFirstTxnScheduling" : "0",
     "boolUseReadA" : "0",
     "boolUseRefresh" : "1",
     "boolUseSBRefresh" : "0",
     "boolUseWriteA" : "0",
     "cmdSchedulingPolicy" : "BANK",
     "debug" : "0",
     "debug_level" : "10",
     "maxPendingWriteThreshold" : "1",
     "minPendingWriteThreshold" : "0.2",
     "nAL" : "0",
     "nBL" : "2",
     "nCCD" : "2",
     "nCCD_L" : "4",
     "nCCD_L_WR" : "2",
     "nCCD_S" : "2",
     "nCL" : "12",
     "nCWL" : "4",
     "nERTR" : "6",
     "nERTW" : "6",
     "nEWTR" : "6",
     "nEWTW" : "6",
     "nFAW" : "16",
     "nRAS" : "28",
     "nRC" : "40",
     "nRCD" : "12",
     "nREFI" : "3900",
     "nRFC" : "350",
     "nRP" : "12",
     "nRRD" : "3",
     "nRRD_L" : "3",
     "nRRD_S" : "2",
     "nRTP" : "3",
     "nRTW" : "13",
     "nWR" : "10",
     "nWTR" : "2",
     "nWTR_L" : "6",
     "nWTR_S" : "3",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numBytesPerTransaction" : "64",
     "numChannels" : "8",
     "numCmdQEntries" : "32",
     "numColsPerBank" : "64",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "numRowsPerBank" : "16384",
     "numTxnQEntries" : "1024",
     "relCommandWidth" : "1",
     "strAddressMapStr" : "r:14_b:2_B:2_l:3_C:3_l:3_c:1_h:6_",
     "strControllerClockFrequency" : "877MHz",
     "txnSchedulingPolicy" : "FRFCFS",
     "verbose" : "0"
})
comp_hbm_cs_ctrl_2.setCoordinates(0, 0, 0)
comp_hbm_cs_ctrl_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_ctrl_2.addLink(link_id_0000001d, "txngenLink", "1000ps")
link_id_0000001e = sst.Link("link_id_0000001e")
comp_hbm_cs_ctrl_2.addLink(link_id_0000001e, "memLink", "1000ps")
comp_hbm_cs_dimm_2 = sst.Component("hbm_cs_dimm_2", "CramSim.c_Dimm")
comp_hbm_cs_dimm_2.addParams({
     "boolPowerCalc" : "0",
     "debug" : "0",
     "debug_level" : "10",
     "nRAS" : "28",
     "nRP" : "12",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numChannels" : "8",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_dimm_2.setCoordinates(0, 0, 0)
comp_hbm_cs_dimm_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_dimm_2.addLink(link_id_0000001e, "ctrlLink", "1000ps")
comp_l2cache_2 = sst.Component("l2cache_2", "memHierarchy.Cache")
comp_l2cache_2.addParams({
     "access_latency_cycles" : "100",
     "associativity" : "96",
     "cache_frequency" : "1312MHz",
     "cache_line_size" : "64",
     "cache_size" : "192KiB",
     "cache_type" : "noninclusive",
     "coherence_protocol" : "MESI",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.addr_range_end" : "17179868672",
     "memNIC.addr_range_start" : "512",
     "memNIC.group" : "2",
     "memNIC.interleave_size" : "256B",
     "memNIC.interleave_step" : "1024B",
     "memNIC.network_bw" : "37.5GB/s",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "mshr_num_entries" : "2048",
     "replacement_policy" : "lru",
     "verbose" : "2"
})
comp_l2cache_2.setCoordinates(0, 0, 0)
comp_l2cache_2.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l2cache_2.addLink(link_id_00000020, "cache", "100ps")
comp_l2cache_2.addLink(link_id_00000021, "low_network_0", "100ps")
comp_mem_l2_bus_3 = sst.Component("mem_l2_bus_3", "memHierarchy.Bus")
comp_mem_l2_bus_3.addParams({
     "bus_frequency" : "4GHz",
     "drain_bus" : "1"
})
comp_mem_l2_bus_3.setCoordinates(0, 0, 0)
comp_mem_l2_bus_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000025 = sst.Link("link_id_00000025")
comp_mem_l2_bus_3.addLink(link_id_00000025, "low_network_0", "100ps")
link_id_00000027 = sst.Link("link_id_00000027")
comp_mem_l2_bus_3.addLink(link_id_00000027, "high_network_0", "100ps")
comp_GPUhbm_3 = sst.Component("GPUhbm_3", "memHierarchy.MemController")
comp_GPUhbm_3.addParams({
     "backend" : "memHierarchy.cramsim",
     "backend.access_time" : "1ns",
     "backend.max_outstanding_requests" : "102400",
     "backend.mem_size" : "17179869184B",
     "backend.request_width" : "64",
     "backing" : "none",
     "clock" : "877MHz",
     "cpulink.accept_region" : "0",
     "cpulink.ack.network_bw" : "32GB/s",
     "cpulink.addr_range_end" : "17179868928",
     "cpulink.addr_range_start" : "768",
     "cpulink.data.network_bw" : "32GB/s",
     "cpulink.fwd.network_bw" : "32GB/s",
     "cpulink.interleave_size" : "256B",
     "cpulink.interleave_step" : "1024B",
     "cpulink.req.network_bw" : "32GB/s",
     "debug" : "0",
     "debug_level" : "10",
     "max_requests_per_cycle" : "-1",
     "verbose" : "0"
})
comp_GPUhbm_3.setCoordinates(0, 0, 0)
comp_GPUhbm_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
link_id_00000022 = sst.Link("link_id_00000022")
comp_GPUhbm_3.addLink(link_id_00000022, "cube_link", "2000ps")
comp_GPUhbm_3.addLink(link_id_00000025, "direct_link", "100ps")
comp_hbm_cs_bridge_3 = sst.Component("hbm_cs_bridge_3", "CramSim.c_MemhBridge")
comp_hbm_cs_bridge_3.addParams({
     "debug" : "0",
     "debug_level" : "10",
     "maxOutstandingReqs" : "102400",
     "mode" : "seq",
     "numBytesPerTransaction" : "32",
     "numTxnPerCycle" : "8",
     "randomSeed" : "0",
     "readWriteRatio" : "0.667",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_bridge_3.setCoordinates(0, 0, 0)
comp_hbm_cs_bridge_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_bridge_3.addLink(link_id_00000022, "cpuLink", "2000ps")
link_id_00000023 = sst.Link("link_id_00000023")
comp_hbm_cs_bridge_3.addLink(link_id_00000023, "memLink", "1000ps")
comp_hbm_cs_ctrl_3 = sst.Component("hbm_cs_ctrl_3", "CramSim.c_Controller")
comp_hbm_cs_ctrl_3.addParams({
     "AddrMapper" : "CramSim.c_AddressHasher",
     "CmdScheduler" : "CramSim.c_CmdScheduler",
     "DeviceDriver" : "CramSim.c_DeviceDriver",
     "TxnConverter" : "CramSim.c_TxnConverter",
     "TxnScheduler" : "CramSim.c_TxnScheduler",
     "bankPolicy" : "OPEN",
     "boolDualCommandBus" : "1",
     "boolEnableQuickRes" : "0",
     "boolMultiCycleACT" : "1",
     "boolReadFirstTxnScheduling" : "0",
     "boolUseReadA" : "0",
     "boolUseRefresh" : "1",
     "boolUseSBRefresh" : "0",
     "boolUseWriteA" : "0",
     "cmdSchedulingPolicy" : "BANK",
     "debug" : "0",
     "debug_level" : "10",
     "maxPendingWriteThreshold" : "1",
     "minPendingWriteThreshold" : "0.2",
     "nAL" : "0",
     "nBL" : "2",
     "nCCD" : "2",
     "nCCD_L" : "4",
     "nCCD_L_WR" : "2",
     "nCCD_S" : "2",
     "nCL" : "12",
     "nCWL" : "4",
     "nERTR" : "6",
     "nERTW" : "6",
     "nEWTR" : "6",
     "nEWTW" : "6",
     "nFAW" : "16",
     "nRAS" : "28",
     "nRC" : "40",
     "nRCD" : "12",
     "nREFI" : "3900",
     "nRFC" : "350",
     "nRP" : "12",
     "nRRD" : "3",
     "nRRD_L" : "3",
     "nRRD_S" : "2",
     "nRTP" : "3",
     "nRTW" : "13",
     "nWR" : "10",
     "nWTR" : "2",
     "nWTR_L" : "6",
     "nWTR_S" : "3",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numBytesPerTransaction" : "64",
     "numChannels" : "8",
     "numCmdQEntries" : "32",
     "numColsPerBank" : "64",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "numRowsPerBank" : "16384",
     "numTxnQEntries" : "1024",
     "relCommandWidth" : "1",
     "strAddressMapStr" : "r:14_b:2_B:2_l:3_C:3_l:3_c:1_h:6_",
     "strControllerClockFrequency" : "877MHz",
     "txnSchedulingPolicy" : "FRFCFS",
     "verbose" : "0"
})
comp_hbm_cs_ctrl_3.setCoordinates(0, 0, 0)
comp_hbm_cs_ctrl_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_ctrl_3.addLink(link_id_00000023, "txngenLink", "1000ps")
link_id_00000024 = sst.Link("link_id_00000024")
comp_hbm_cs_ctrl_3.addLink(link_id_00000024, "memLink", "1000ps")
comp_hbm_cs_dimm_3 = sst.Component("hbm_cs_dimm_3", "CramSim.c_Dimm")
comp_hbm_cs_dimm_3.addParams({
     "boolPowerCalc" : "0",
     "debug" : "0",
     "debug_level" : "10",
     "nRAS" : "28",
     "nRP" : "12",
     "numBankGroupsPerRank" : "4",
     "numBanksPerBankGroup" : "4",
     "numChannels" : "8",
     "numPChannelsPerChannel" : "2",
     "numRanksPerChannel" : "1",
     "strControllerClockFrequency" : "877MHz",
     "verbose" : "0"
})
comp_hbm_cs_dimm_3.setCoordinates(0, 0, 0)
comp_hbm_cs_dimm_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_hbm_cs_dimm_3.addLink(link_id_00000024, "ctrlLink", "1000ps")
comp_l2cache_3 = sst.Component("l2cache_3", "memHierarchy.Cache")
comp_l2cache_3.addParams({
     "access_latency_cycles" : "100",
     "associativity" : "96",
     "cache_frequency" : "1312MHz",
     "cache_line_size" : "64",
     "cache_size" : "192KiB",
     "cache_type" : "noninclusive",
     "coherence_protocol" : "MESI",
     "debug" : "0",
     "debug_level" : "10",
     "memNIC.addr_range_end" : "17179868928",
     "memNIC.addr_range_start" : "768",
     "memNIC.group" : "2",
     "memNIC.interleave_size" : "256B",
     "memNIC.interleave_step" : "1024B",
     "memNIC.network_bw" : "37.5GB/s",
     "memNIC.network_link_control" : "shogun.ShogunNIC",
     "mshr_num_entries" : "2048",
     "replacement_policy" : "lru",
     "verbose" : "2"
})
comp_l2cache_3.setCoordinates(0, 0, 0)
comp_l2cache_3.enableAllStatistics({
     "type" : "sst.AccumulatorStatistic"
})
comp_l2cache_3.addLink(link_id_00000026, "cache", "100ps")
comp_l2cache_3.addLink(link_id_00000027, "low_network_0", "100ps")
# Define SST Statistics Options:
sst.setStatisticLoadLevel(16)
sst.setStatisticOutput("sst.statOutputCSV", {
     "filepath" : "test-out-600k-c.csv",
     "separator" : ", "
})
# End of generated output.

